---
- hosts: cloud
  tasks :
  - lvol:
        vg: guru
        lv: "{{ lvname }}"
        size: "{{ lvsize}}"
  - filesystem:
        fstype: "ext4"
        dev: "/dev/guru/{{ lvname }}"
  - file:
        path: "/mnt/{{ lvname }}"
        state: "directory"
  - mount:
        path: "/mnt/{{ lvname }}"
        src: "/dev/guru/{{ lvname }}"
        fstype: ext4
        state: "mounted"                    
  - shell: "echo '/mnt/{{ lvname }} 172.20.10.6(rw,no_root_squash)'>> /etc/exports"
  - service:
        name: nfs
        enabled: True 
        state: restarted
  - firewalld:
        permanent: true
        state: disabled 
  - command: "iptables -F"    




- hosts: client
  tasks:
  - file:
      path: "/media/{{ lvname }}"
      state: directory
  - shell: "mount 172.20.10.5:/mnt/{{ lvname }} /media/{{ lvname }}" 
